/**
 * Google Fonts available for admin typography selection.
 * Loaded via Google Fonts CSS API; names must match Google Fonts family names.
 */
export const GOOGLE_FONT_OPTIONS: string[] = [
  'Playfair Display',
  'Lora',
  'Merriweather',
  'Source Serif 4',
  'PT Serif',
  'Libre Baskerville',
  'Crimson Pro',
  'Literata',
  'DM Serif Display',
  'Fraunces',
  'Bodoni Moda',
  'EB Garamond',
  'Cormorant Garamond',
  'Bitter',
  'Vollkorn',
  'Libre Baskerville',
  'Spectral',
  'Crimson Text',
  'Lora',
  'Newsreader',
  'Sora',
  'DM Sans',
  'Inter',
  'Open Sans',
  'Roboto',
  'Lato',
  'Montserrat',
  'Nunito',
  'Poppins',
  'Work Sans',
  'Raleway',
  'Oswald',
  'Source Sans 3',
  'Ubuntu',
  'Nunito Sans',
  'Rubik',
  'Fira Sans',
  'Quicksand',
  'Karla',
  'Manrope',
  'Figtree',
  'Outfit',
  'Plus Jakarta Sans',
  'Lexend',
  'Space Grotesk',
  'Bebas Neue',
  'Anton',
  'Archivo',
  'Barlow',
  'Barlow Condensed',
  'Cabin',
  'Exo 2',
  'Josefin Sans',
  'Libre Franklin',
  'Maven Pro',
  'Mulish',
  'Noto Sans',
  'Oxygen',
  'Rajdhani',
  'Red Hat Display',
  'Roboto Condensed',
  'Roboto Mono',
  'Titillium Web',
  'Trirong',
  'Yanone Kaffeesatz',
  'Abhaya Libre',
  'Abril Fatface',
  'Alegreya',
  'Alegreya Sans',
  'Alfa Slab One',
  'Amatic SC',
  'Architects Daughter',
  'Arimo',
  'Arsenal',
  'Asap',
  'Balsamiq Sans',
  'Barlow Semi Condensed',
  'BenchNine',
  'Bodoni Moda',
  'Caveat',
  'Chakra Petch',
  'Cinzel',
  'Comfortaa',
  'Commissioner',
  'Cormorant',
  'Crimson Pro',
  'Dancing Script',
  'Didact Gothic',
  'Dosis',
  'DynaPuff',
  'Epilogue',
  'Fahkwang',
  'Familjen Grotesk',
  'Fira Code',
  'Fjalla One',
  'Forum',
  'Gabarito',
  'Gloock',
  'Great Vibes',
  'Gruppo',
  'Hanken Grotesk',
  'Heebo',
  'Inconsolata',
  'Inria Sans',
  'Instrument Sans',
  'Instrument Serif',
  'Italiana',
  'Jost',
  'Jersey 25',
  'JetBrains Mono',
  'Kanit',
  'Karla',
  'Khand',
  'Knewave',
  'Krona One',
  'Labrada',
  'League Spartan',
  'Libre Caslon Display',
  'Libre Franklin',
  'Lilita One',
  'Londrina Solid',
  'Madimi One',
  'Marcellus',
  'Martel',
  'Martel Sans',
  'Merriweather Sans',
  'M PLUS 1p',
  'M PLUS Rounded 1c',
  'Mukta',
  'Nanum Gothic',
  'Neuton',
  'Noto Serif',
  'Noto Serif Display',
  'NTR',
  'Old Standard TT',
  'Onest',
  'Orelega One',
  'Overpass',
  'Pacifico',
  'Passion One',
  'Patua One',
  'Permanent Marker',
  'Petit Formal Script',
  'Philosopher',
  'Playfair Display SC',
  'Playwrite',
  'Prata',
  'Prompt',
  'Protest Riot',
  'Protest Revolution',
  'Public Sans',
  'Quicksand',
  'Rethink Sans',
  'Righteous',
  'Roboto Flex',
  'Roboto Slab',
  'Rokkitt',
  'Rufina',
  'Russo One',
  'Saira',
  'Saira Condensed',
  'Satisfy',
  'Schibsted Grotesk',
  'Send Flowers',
  'Shadows Into Light',
  'Signika',
  'Signika Negative',
  'Silkscreen',
  'Slabo 27px',
  'Source Code Pro',
  'Space Mono',
  'Spectral SC',
  'Syne',
  'Taviraj',
  'Tenor Sans',
  'Tinos',
  'Truculenta',
  'Tsukimi Rounded',
  'Ubuntu Condensed',
  'Ubuntu Mono',
  'Unbounded',
  'Unna',
  'Urbanist',
  'Varela Round',
  'Victor Mono',
  'Volkhov',
  'Wix Madefor Display',
  'Wix Madefor Text',
  'Xanh Mono',
  'Yeseva One',
  'Young Serif',
  'Zeyada',
  'Zilla Slab',
]

/** Default heading font when none selected (Montserrat for headings/subheadings). */
export const DEFAULT_HEADING_FONT = 'Montserrat'

/** Default body font when none selected (Lato). */
export const DEFAULT_BODY_FONT = 'Lato'

/**
 * Build Google Fonts CSS2 URL for one or more families (regular 400, 600, 700).
 */
export function googleFontsUrl(families: string[]): string {
  const familyParam = families
    .filter(Boolean)
    .map((f) => `family=${encodeURIComponent(f).replace(/%20/g, '+')}:wght@400;600;700`)
    .join('&')
  return `https://fonts.googleapis.com/css2?${familyParam}&display=swap`
}
